### ISSUE TITLE
Although Data Is Persisted Across Node Reboots, It Does Not Persist In The Pin Store

### ISSUE THREAD

**Issue by postables** [ipfs/go-ds-s3#10]
Been experimenting with this plugin running an IPFS node, and have noticed that although I may restart my IPFS node which is using this datastore, and the data does remain stored long-term, subsequent queries such as `ipfs pin ls` indicate that nothing is pinned, which doesn't match what I'm seeing within my S3 datastore minio.

I think this might be in part caused by https://github.com/ipfs/go-ds-s3/issues/2 but I'm not sure what the actual issue is.

**Comment by Stebalien** [comment]
So, that issue has actually since been fixed (I think). What's your datastore config look like?

We store the pinset in `/local/pins`. Is this object not present in your S3 bucket?

**Comment by postables** [comment]
here is the entire datastore config
```json
    "Datastore": {
    "StorageMax": "10GB",
    "StorageGCWatermark": 90,
    "GCPeriod": "1h",
    "Spec": {
      "mounts": [
        {
          "child": {
            "accessKey": "C03T49S17RP0APEZDK6M",
            "secretKey": "q4I9t2MN/6bAgLkbF6uyS7jtQrXuNARcyrm2vvNA",
            "bucket": "go-ipfs-storj-4",
            "region": "us-east-1",
            "regionEndpoint": "http://127.0.0.1:9000",
            "rootDirectory": "",
            "type": "s3ds"
          },
          "mountpoint": "/blocks",
          "name": "s3ds",
          "type": "log"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "HashOnRead": false,
    "BloomFilterSize": 1000000000
  },
```

nope when i access the bucket I do not see anything resembling `/local/pins`

**Comment by postables** [comment]
Well I feel a bit stupid,  the modified version i was playing with to learn how it works was missing a crucial piece, when I declared my `Batch` function I missed including the workers so

```golang
// Batch is a batched datastore operations
func (d *Datastore) Batch() (ds.Batch, error) {
	return &dBatch{
		d:       d,
		ops:     make(map[string]dBatchOp),
	}, nil
}
```

needed to be:

```golang
// Batch is a batched datastore operations
func (d *Datastore) Batch() (ds.Batch, error) {
	return &dBatch{
		d:       d,
		ops:     make(map[string]dBatchOp),
		workers: d.Workers,
	}, nil
}
```

I'll close this since I seem to have solved my issue, and have now learned enough to make sense of the plugin and datastore system, woot!

**Comment by Stebalien** [comment]
Looking at that config, you're not storing your pinset on S3. Your current datastore tree looks like:

* Mount: this is a datastore that _mounts_ sub-datastores in various namespaces
  * LevelDB - mounted at /
  * S3 - mounted at /blocks

That means _blocks_ will be stored on S3 but everything else will be stored locally. Honestly, this is probably the best way to do it but it _does_ mean that only blocks will be persisted to S3.

**Comment by woss** [comment]
this is still an issue. today i checked and the pinning doesn't work when mounted to the s3 bucket. 

`ipfs pin add CID` fails with error `Error: failed to enqueue CID: shutting down

Can Protocol Labs officially support this plugin so we can rely on it?
Thanks
