### ISSUE TITLE
Impact of multiple IPFS processes sharing a S3 bucket

### ISSUE THREAD

**Issue by wehriam** [ipfs/go-ds-s3#103]
What would be the impact of multiple IPFS instances sharing the same S3 bucket?

**Comment by Stebalien** [comment]
You can't share `/`. That'll break pins, etc. However, you can share `/blocks` as long as you disable garbage collection. You can combine multiple datastores with https://github.com/ipfs/go-ipfs/blob/master/docs/datastores.md#mount, see https://github.com/ipfs/go-ds-s3#configuration for an example.

**Comment by wehriam** [comment]
@Stebalien - Are you aware of any way to implement garbage collection using an S3 bucket shared by multiple nodes? (Restarting nodes, disabling GC on all but one node, manually calling [block rm](https://docs.ipfs.io/reference/cli/#ipfs-block-rm), etc...)

**Comment by Stebalien** [comment]
That depends on how you're using the shared datastore. For example, you could have one node manage pins and not pin anything on any of the other nodes. That should let you turn on garbage collection in the node managing all the pins.

**Comment by wehriam** [comment]
Would it be correct to state that the primary caveat of multiple nodes sharing the same S3 bucket mounted to `/blocks` is that a node might incorrectly garbage collect blocks pinned by another node?

**Comment by Stebalien** [comment]
Yes.

**Comment by jacobheun** [comment]
Closing this as the questions seems to be answered.

**Comment by obo20** [comment]
@Stebalien from doing further testing on this, I was unable to get garbage collection at all for this plugin. I was able to use `ipfs block rm` successfully but `ipfs repo gc` returned nothing and no blocks were removed from the s3 bucket. 

Is this a known bug?

**Comment by Stebalien** [comment]
No, deleting blocks should work. The only thing I can think of is that querying for blocks is somehow broken. Let's discuss in a new issue, _this_ issue is about the safety of sharing a single S3 store between multiple IPFS daemons (with potentially different pin-sets).

**Comment by Stebalien** [comment]
Ah, should have read your second message: https://github.com/ipfs/go-ds-s3/issues/198
