### ISSUE TITLE
Excessive Has()/GetSize() calls, caching?

### ISSUE THREAD

**Issue by ShadowJonathan** [ipfs/go-ds-s3#113]
I'm currently having a problem with using this plugin for b2 backblaze storage, which has an s3 API, they charge for "Class B" transactions, under which `HeadObject` falls, which `GetSize` uses, which in turn is used by `Has()`

As far as I know, `Has()` is called every time a bitswap request comes over the network, to see if the block can be provided to the other node, with the rate at which this happens, however, the transactions quickly build up, and I'm looking at a 300K transaction count just after bringing this node up for just 5 hours.

That in turn translates to some significant monthly extra costs, is it possible to "cache" the keys available in the s3 bucket? To perform a `ListObjects` call every minute or so, and to update a local "Key List" file which'd every `Has` call will be validated against (performing no calls to the s3 api), a `Put` should then automatically add that key to the list.

**Comment by ShadowJonathan** [comment]
This "Key List" could possibly also just exist in memory, though that could become problematic if simply too many keys exist in the s3 bucket (which is very possible, as these buckets can become quite large)

**Comment by ShadowJonathan** [comment]
I discovered that GetSize() is getting a sizable amount of calls as well, through profiling it in `/debug/metrics/`, maybe some caching could help there as well

**Comment by aschmahmann** [comment]
@MichaelMure any thoughts?

**Comment by Stebalien** [comment]
@ShadowJonathan the right way to deal with this is to use the bloom filter cache: https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#datastorebloomfiltersize. However, this _will_ list every block you have on start.

**Comment by Stebalien** [comment]
There's also an ARC cache to remember whether or not we have blocks (and their sizes). Unfortunately, the size of that cache is not tunable. See https://github.com/ipfs/go-ipfs-config/pull/41 for some WIP work there.

In general, modifying this datastore directly is not the right approach

**Comment by Stebalien** [comment]
Note: I'm happy to re-open this if you disagree. I just don't want to leave it around given how old it is.
