### ISSUE TITLE
more detailed documentation ?

### ISSUE THREAD

**Issue by MichaelMure** [ipfs/go-ds-s3#12]
I was trying to test this plugin, but I can't find a way to load the plugin properly in go-ipfs. I tried various things, using a go-ipfs binary from dist.ipfs.io, compile go-ipfs myself, changing various import path in this plugin, injecting this plugin as an internal one ...

The last error I get is:

> ERROR   cmd/ipfs: error loading plugins:  loading plugin /home/michael/.ipfs/plugins/s3plugin.so: plugin.Open("/home/michael/.ipfs/plugins/s3plugin"): plugin was built with a different version of package gx/ipfs/QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP/goprocess main.go:65

Could you detail a bit more the building an install process ? Could you also provide an example of configuration ?

Thanks !

**Comment by Stebalien** [comment]
Oh, damn. This is _so_ broken but should get better now that we've moved go modules. We're going to cut a release ASAP (like, next week). I can fix that when we do.

**Comment by Stebalien** [comment]
"this week". But it _has_ been released now.

Anyone want to update this for go-ipfs 0.4.20, @ipfs/go-team?

**Comment by Stebalien** [comment]
Sorry, "this" is https://github.com/ipfs/go-ds-s3/issues/13.

**Comment by autonome** [comment]
Updated plugin docs: https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md
