### ISSUE TITLE
Is this working for IPFS v0.6.0?

### ISSUE THREAD

**Issue by Rick7C2** [ipfs/go-ds-s3#122]
I'm trying to install this plugin for IPFS v0.6.0 but it's not working for me. Is it updated to work for this version yet?

When I try to bundle I get this...

```
make build
go version go1.14.4 linux/amd64
bin/check_go_version 1.14.2
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go build  "-asmflags=all='-trimpath='" "-gcflags=all='-trimpath='" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=5a1953922-dirty" -o "cmd/ipfs/ipfs" "github.com/ipfs/go-ipfs/cmd/ipfs"
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
make: *** [cmd/ipfs/Rules.mk:22: cmd/ipfs/ipfs] Error 1
```

When I try to install as a plugin I get errors when trying to ipfs init...

```
make IPFS_VERSION=v0.6.0 install
./set-target.sh v0.6.0
go build  -asmflags=all=-trimpath="" -gcflags=all=-trimpath="" -buildmode=plugin -o "s3plugin.so" "plugin/main/main.go"
chmod +x "s3plugin.so"
Built against v0.6.0
install -Dm700 s3plugin.so "/root/.ipfs/plugins/go-ds-s3.so"
ipfs init --profile server
Error: error loading plugins: loading plugin /root/.ipfs/plugins/go-ds-s3.so: plugin.Open("/root/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package github.com/jbenet/goprocess
```

Am I doing something wrong or is it just not ready yet?

**Comment by aschmahmann** [comment]
@Rick7C2 try using the version of go-ipfs v0.6.0 distributed under go-ipfs Releases on GitHub or dist.ipfs.io

**Comment by Rick7C2** [comment]
When bundling I used https://github.com/ipfs/go-ipfs/tree/release-v0.6.0

When trying to install via plugin I installed IPFS via ipfs-update install v0.6.0

I will try again via dist.ipfs.io just to be sure.

**Comment by Rick7C2** [comment]
When I try to bundle I noticed that when running this command...

`go get github.com/ipfs/go-ds-s3@latest`

It grabs version 0.5.0 I assume because that is the latest version in the releases on github. So that will not work untill that is updated to 0.6.0

I just don't understand this error when running the init and any ipfs command after installing the plugin...

Error: error loading plugins: loading plugin /root/.ipfs/plugins/go-ds-s3.so: plugin.Open("/root/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package github.com/jbenet/goprocess

What version should jbenet/goprocess be and how do I change it? I assume when I tried to bundle with the go get command above I downloaded goprocess version needed for v0.5.0

**Comment by Rick7C2** [comment]
My latest attempt using this https://github.com/ipfs/go-ds-s3/issues/98#issuecomment-647737064 as a guide...

```# git clone https://github.com/ipfs/go-ipfs.git
Cloning into 'go-ipfs'...
remote: Enumerating objects: 111, done.
remote: Counting objects: 100% (111/111), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 99981 (delta 65), reused 48 (delta 30), pack-reused 99870
Receiving objects: 100% (99981/99981), 39.85 MiB | 23.12 MiB/s, done.
Resolving deltas: 100% (66752/66752), done.
# git clone https://github.com/ipfs/go-ds-s3.git
Cloning into 'go-ds-s3'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 694 (delta 7), reused 0 (delta 0), pack-reused 677
Receiving objects: 100% (694/694), 609.15 KiB | 7.25 MiB/s, done.
Resolving deltas: 100% (251/251), done.
# cd go-ipfs
# git checkout release-v0.6.0
Branch 'release-v0.6.0' set up to track remote branch 'release-v0.6.0' from 'origin'.
Switched to a new branch 'release-v0.6.0'
# cd ~/go-ds-s3
# git checkout release/v0.6.0
Branch 'release/v0.6.0' set up to track remote branch 'release/v0.6.0' from 'origin'.
Switched to a new branch 'release/v0.6.0'
# cd ~/go-ipfs/
# make install
go version go1.14.4 linux/amd64
bin/check_go_version 1.14.2
plugin/loader/preload.sh > plugin/loader/preload.go
go fmt plugin/loader/preload.go >/dev/null
go install  "-asmflags=all='-trimpath='" "-gcflags=all='-trimpath='" -ldflags="-X "github.com/ipfs/go-ipfs".CurrentCommit=5a1953922" ./cmd/ipfs
# pwd
/root/go-ipfs
# cd ~/go-ds-s3/
# make IPFS_VERSION=/root/go-ipfs install
./set-target.sh /root/go-ipfs
go build  -asmflags=all=-trimpath="" -gcflags=all=-trimpath="" -buildmode=plugin -o "s3plugin.so" "plugin/main/main.go"
chmod +x "s3plugin.so"
Built against /root/go-ipfs
install -Dm700 s3plugin.so "/root/.ipfs/plugins/go-ds-s3.so"
# ipfs version
Error: error loading plugins: loading plugin /root/.ipfs/plugins/go-ds-s3.so: plugin.Open("/root/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package github.com/jbenet/goprocess

**Comment by PyR8zdl** [comment]
Could someone share a step by step commands that work for them with v0.6.0?

**Comment by Rick7C2** [comment]
I tried installing on a CentOS 8 machine recently and same issues as Ubuntu.

Has anyone been able to get this working on 0.6.0? Mind sharing the steps you took?

**Comment by aschmahmann** [comment]
On Ubuntu 20.04.1 LTS

```
rm ~/.ipfs/plugins/*
cd ~/go/src/github.com/ipfs/go-ds-s3
ipfs update fetch v0.6.0
make install IPFS_VERSION=v0.6.0
./ipfs-v0.6.0 daemon
```

**Comment by Rick7C2** [comment]
ok I think I found what was wrong. If you download go-ds-s3 via `go get github.com/ipfs/go-ds-s3` it works. if you do a git clone it doesn't.

Thanks, @aschmahmann I've finally got this working! :D

**Comment by aschmahmann** [comment]
Glad you got it working. FWIW I did a git clone and everything was just fine.
