### ISSUE TITLE
Multiple IPFS instances one S3 bucket. Is this possible?

### ISSUE THREAD

**Issue by Rick7C2** [ipfs/go-ds-s3#124]
I want to set up multiple IPFS instances around the world that share the same S3 datastore.

Only one IPFS instance would need to be able to write to the S3 bucket. The rest will only read the data on S3 and serve the content via IPFS.

Is this possible with the S3 datastore? If so how would I go about doing this?

I've got two VPS's with IPFS and the S3 plugin setup to use the same bucket. I add and pin a file on one then shut that IPFS server down.

I then try to receive the file from an IPFS client bootstrapped to the second IPFS server attached to the S3 bucket and nothing happens.

**Comment by aschmahmann** [comment]
cc @MichaelMure any thoughts or ideas here? It seems like if you don't GC then you could potentially share a blockstore (not the whole datastore) across a number of repos.

**Comment by Rick7C2** [comment]
Seems this was already asked here... https://github.com/ipfs/go-ds-s3/issues/19

Is this just speculation or would this actually work in RO mode?

Is there a way to make IPFS RO?

**Comment by Stebalien** [comment]
Not really. Basically, you _can_ share a single S3 bucket, but it's a "you need to know what you're doing" kind of thing.
