### ISSUE TITLE
Error loading plugin on ipfs v0.7.0

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ds-s3#126]
I've built this against the pre-built go-ipfs v0.7.0 with
> make install IPFS_VERSION=v0.7.0

My go version matches that used to build go-ipfs: https://dist.ipfs.io/go-ipfs/v0.7.0/build-info
> go version go1.14.4 linux/amd64

When I try to load the plugin it errors with:
> Error: error loading plugins: loading plugin /tmp/peergos15169824593847595019/.ipfs/plugins/go-ds-s3.so: plugin.Open("/tmp/peergos15169824593847595019/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package internal/cpu

**Comment by MichaelMure** [comment]
See https://github.com/ipfs/go-ds-s3/pull/127

**Comment by aschmahmann** [comment]
Was fixed by the above PR
