### ISSUE TITLE
plugin was built with a different version of package

### ISSUE THREAD

**Issue by DeveloperInProgress** [ipfs/go-ds-s3#184]
I get the following error when I run `ipfs daemon`

`ERROR: install failed: version check failed: Error: error loading plugins: loading plugin /home/ec2-user/.ipfs/plugins/go-ds-s3.so: plugin.Open("/home/ec2-user/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package github.com/google/uuid`

how may I rectify this error?

**Comment by aschmahmann** [comment]
@DeveloperInProgress Go plugins can be pretty finicky and you have to build with matching versions (e.g. the latest go-ds-s3 and go-ipfs). Similarly if you don't follow the build instructions (https://github.com/ipfs/go-ds-s3#building-and-installing) things will tend to go wrong.

As mentioned in the README you will probably have a better time preloading the plugin into go-ipfs then building as a separate library (as a bonus the plugin will also be usable on Windows 😄). https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins

If you have any more questions ask on discuss.ipfs.io, and feel free to tag me, as it is much better suited for general support and helping people who run into issues in the future find your issue (nobody really looks at closed GitHub Issues).
