### ISSUE TITLE
Getting error of `Error: unknown datastore type: s3ds` with a clean new ipfs node

### ISSUE THREAD

**Issue by KoushikGavini** [ipfs/go-ds-s3#187]
I am playing around with the go-ds-s3 implementation and having an issue bringing ipfs node with s3ds as the datastore on a brand new ipfs instance. 
`Error: unknown datastore type: s3ds`

IPFS Specs:
```text
go-ipfs version: 0.9.0
Repo version: 11
System version: amd64/linux
Golang version: go1.16.5
```
Below are the steps I have taken: 

1. Turned on modules 
> export GO111MODULE=on

2. Cloned go-ipfs, pulled in datastore plugin, and added plugin to the preload list

```shell
git clone https://github.com/ipfs/go-ipfs
cd go-ipfs
go get github.com/ipfs/go-ds-s3@latest
echo "s3ds github.com/ipfs/go-ds-s3/plugin 0" >> plugin/loader/preload_list
```

3. Rebuild go-ipfs plugin and install go-ipfs

```shell
Make build
Make install
```

4. Run IPFS init, edit Datastore in the config file (/.ipfs/config), edit data_store_spec

* Config file
```json
  "Datastore": {
    "StorageMax": "10GB",
    "StorageGCWatermark": 90,
    "GCPeriod": "1h",
    "Spec": {
      "mounts": [
        {
          "child": {
            "type": "s3ds",
            "region": "us-east-2",
            "bucket": "test-bucket-2",
            "rootDirectory": "test_root",
            "accessKey": "",
            "secretKey": ""
          },
          "mountpoint": "/blocks",
          "prefix": "s3.datastore",
          "type": "measure"
        },
        {
          "child": {
            "compression": "none",
            "path": "datastore",
            "type": "levelds"
          },
          "mountpoint": "/",
          "prefix": "leveldb.datastore",
          "type": "measure"
        }
      ],
      "type": "mount"
    },
    "HashOnRead": false,
    "BloomFilterSize": 0
  },
```

* Data_store_spec

```json

{
  "mounts": [
    {
      "bucket": "test-bucket-2",
      "mountpoint": "/blocks",
      "region": "us-east-2",
      "rootDirectory": "test_root"
    },
    {
      "mountpoint": "/",
      "path": "datastore",
      "type": "levelds"
    }
  ],
  "type": "mount"
```

5. Take node online 
> ipfs daemon

* Getting error
```shell
Error: unknown datastore type: s3ds
```

**Comment by Stebalien** [comment]
My crystal ball says.... wrong IPFS binary. `make install` probably installed into the wrong location. Check `which ipfs`.

Otherwise, I'd expect `ipfs version --all` to return something of the form `v0.Y.0-dev-d2asfd-dirty`.

**Comment by BigLep** [comment]
Closing for now due to inactivity. Feel free to reopen if this is still an issue.

**Comment by aliiqbal436** [comment]
@KoushikGavini any progress? i'm facing this same issue.

**Comment by keiner5212** [comment]
To use "type: s3ds" you need to install the plugin https://github.com/ipfs/go-ds-s3
