### ISSUE TITLE
Sharding?

### ISSUE THREAD

**Issue by v-stickykeys** [ipfs/go-ds-s3#199]
By default, go-ipfs provides a sharding option for the datastore. When using this plugin the datastore is not being sharded.

As described in [previous issues](https://github.com/ipfs/go-ds-s3/issues/17#issuecomment-499250568), the serialization in the `datastore_spec` is not 1:1 because when I try to add `shardFunc` this results in an error.

Is there a way to achieve sharding for the data stored in S3?

**Comment by Stebalien** [comment]
Specifically, the _flatfs_ (flat-file backed datastore) provides a sharding option because some filesystems don't handle large directories very well. None of the other datastores provide such an option.

Honestly, sharding just doesn't make sense in S3 and would massively complicate the query logic.

**Comment by v-stickykeys** [comment]
@Stebalien Would be great to know why you think so, as the [js-ipfs plugin for s3](https://github.com/ipfs/js-datastore-s3) *does* support sharding and in our case it has been useful to prevent rate limiting from s3.

We really don't see it as possible to use this plugin as it is without sharding.
cc @zachferland to provide any additional thoughts.

**Comment by v-stickykeys** [comment]
Also @Stebalien please see this discussion about why sharding is useful in s3 in general and more specifically why it is useful for IPFS s3 datastore: https://github.com/ipfs/js-datastore-s3/issues/27

**Comment by Stebalien** [comment]
Interesting, I stand corrected.

In javascript, this isn't actually a feature in the s3 datastore but in a "wrapper" datastore that transforms keys. That's probably the correct way to implement this and that implementation would live in https://github.com/ipfs/go-datastore/.

However, it's going to be non-trivial to correctly handle queries, offsets, etc. Basically, every query would need to iterate over all shards at the same time, interleaving the results.

If you want to submit a datastore to do this, take a look at how queries are handled in https://github.com/ipfs/go-datastore/blob/ed11f242ef104130b10a1e86728ab3779cd23c64/mount/mount.go#L209.
