### ISSUE TITLE
Hi, I install S3 plugin. My IPFS version is 0.4.15. When I restart IPFS, I got this error message "Error: unknown datastore type: s3ds"   Can you help me?

### ISSUE THREAD

**Issue by tghafarian** [ipfs/go-ds-s3#203]

**Comment by aschmahmann** [comment]
go-ipfs v0.4.15 is ancient (May 12th, 2018), try using the latest version of go-ipfs (v0.10.0). It looks like datastore plugins weren't even supported back then https://github.com/ipfs/go-ipfs/pull/5187. If you're having issues with the latest version of go-ipfs you can ask for help on discuss.ipfs.io.
