### ISSUE TITLE
Build error for IPFS_VERSION v0.10.0

### ISSUE THREAD

**Issue by hwnahm** [ipfs/go-ds-s3#204]
macOS Monterey
Verion 12.0.1

go version go1.17.3 darwin/amd64

======================================

% git clone https://github.com/ipfs/go-ds-s3.git
% make IPFS_VERSION=v0.10.0
% make install
./set-target.sh v0.10.0
go build  -trimpath -buildmode=plugin -o "s3plugin.so" "plugin/main/main.go"
# github.com/klauspost/compress/zstd/internal/xxhash
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/Users/peter/go/pkg/mod/github.com/klauspost/compress@v1.11.7/zstd/internal/xxhash/xxhash_amd64.s:120)	ADDQ	R15, AX
asm: assembly failed
# github.com/cespare/xxhash/v2
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/Users/peter/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash_amd64.s:120)	ADDQ	R15, AX
asm: assembly failed
make: *** [s3plugin.so] Error 2

**Comment by kaloyan-raev** [comment]
I got the same error when I tried to build with Go 1.17.3. Then I tried with Go 1.16.8, and the build was successful.

**Comment by evgromov** [comment]
hey guys, I have same problem 

> ipfs version v0.10.0
> go version 1.16.8
> go-ds-s3 - last master

`Error: error loading plugins: loading plugin /data/ipfs/plugins/go-ds-s3.so: plugin.Open("/data/ipfs/plugins/go-ds-s3"): plugin was built with a different version of package github.com/ipfs/go-datastore/query`

may be someone found solutions?
Im try to fix this 3 day..

**Comment by aschmahmann** [comment]
This is https://github.com/ipfs/go-ipfs/issues/8550. You can either build without the `make install` script or use Go 1.16 until this is fixed.
