### ISSUE TITLE
plugin was built with a different version of package github.com/aws/aws-sdk-go/aws/awserr

### ISSUE THREAD

**Issue by jian-guo-s** [ipfs/go-ds-s3#208]

**Comment by guseggert** [comment]
Can you elaborate on what your issue is here?

**Comment by jian-guo-s** [comment]
> Can you elaborate on what your issue is here?

Thank you very much for your reply. My purpose is to build an ipfs that supports s3 locally. First, I will locally make bild and make install of go-ds-s3 of v0.7.0, and then make build of go-ipfs of v0.8.0, and Initialize, then configure ~/.ipfs/config and ~/.ipfs/datastore_spec, and finally ipfs daemon, an error occurs: ERROR cmd/ipfs error from node construction: could not build arguments for function "reflect".makeFuncStub (/usr /local/go/src/reflect/asm_amd64.s:12): failed to build *mfs.Root: received non-nil error from function "github.com/ipfs/go-ipfs/core/node".Files (/ tmp/go-ipfs-0.8.0/core/node/core.go:106): failure writing to dagstore: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Error: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *mfs.Root: received non-nil error from function "github. com/ipfs/go-ipfs/core/node".Files (/tmp/go-ipfs-0.8.0/core/node/core.go:106): failure writing to dagstore: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
The version of go is v1.15.8

**Comment by aschmahmann** [comment]
I suspect if you follow the instructions in this repo for bundling (https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins) which are essentially the docs for building a preloaded plugin with go-ipfs (https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins) that you will have a much easier time getting things to run.

You will also be able to better control the dependencies for the built binary. It looks like you have some errors with your AWS configuration and might want to enable more verbose logging within the s3 datastore code to get more output.

> plugin was built with a different version of package github.com/aws/aws-sdk-go/aws/awserr

This doesn't show up in your output at all.

**Comment by jian-guo-s** [comment]
> 我怀疑您是否按照此 repo 中的说明进行捆绑（https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins），它们本质上是用于构建预加载的文档带有 go-ipfs ( https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins ) 的插件，您将有更轻松的时间让事情运行。
> 
> 您还可以更好地控制构建的二进制文件的依赖项。看起来您的 AWS 配置有一些错误，并且可能希望在 s3 数据存储代码中启用更详细的日志记录以获得更多输出。
> 
> > 插件是用不同版本的包 github.com/aws/aws-sdk-go/aws/awserr 构建的
> 
> 这根本不会出现在您的输出中。

Thank you very much for your reply. I bundled the plug-in with ipfs and configured ~/.ipfs. After executing the ipfs daemon, another error occurred: ERROR cmd/ipfs error from node construction: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *mfs.Root: received non-nil error from function "github.com/ipfs/go-ipfs/ core/node".Files (/tmp/go-ipfs-0.8.0/core/node/core.go:106): failure writing to dagstore: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Error: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *mfs.Root: received non-nil error from function "github. com/ipfs/go-ipfs/core/node".Files (/tmp/go-ipfs-0.8.0/core/node/core.go:106): failure writing to dagstore: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors

**Comment by aschmahmann** [comment]
Is this still an issue for you with later go-ipfs versions?

**Comment by guseggert** [comment]
`NoCredentialProviders: no valid providers in chain` means that the default credentials providers were unable to find AWS credentials. See the docs here: https://docs.aws.amazon.com/sdk-for-go/v1/developer-guide/configuring-sdk.html#specifying-credentials

Feel free to reopen if you have more questions.
