### ISSUE TITLE
go: error loading module requirements 

### ISSUE THREAD

**Issue by vaultec81** [ipfs/go-ds-s3#21]
All other dependencies installed correctly... Same result on both Linux amd64, arm64. 

```
$ make go.mod IPFS_VERSION=v0.4.21             ./set-target.sh v0.4.21
go: github.com/dgraph-io/badger@v2.0.0-rc.2+incompatible: go.mod has post-v2 module path "github.com/dgraph-io/badger/v2" at revision v2.0.0-rc.2
go: error loading module requirements
Makefile:20: recipe for target 'go.mod' failed
make: *** [go.mod] Error 1
```

go version go1.12.7 linux/amd64

**Comment by Stebalien** [comment]
Badger messed with their tags a bit. go-ipfs 0.4.22 is now out (uploading the blog post now) so I recommend you use that.

Also, unlike 0.4.21, it actually _works_ with plugins out of the box (see https://github.com/ipfs/go-ds-s3/issues/17).

**Comment by vaultec81** [comment]
I see, thank you for the quick response.
