### ISSUE TITLE
 plugin was built with a different version of package github.com/ipfs/go-datastore/query

### ISSUE THREAD

**Issue by evgromov** [ipfs/go-ds-s3#215]
Hello, guys, I'm checked all issues and this not helped me.(

specification:
> ipfs version v0.10.0 
> go version 1.16.8 
> go-ds-s3 - last master

`Error: error loading plugins: loading plugin  /data/ipfs/plugins/go-ds-s3.so:  plugin.Open("/data/ipfs/plugins/go-ds-s3"): plugin was built with a  different version of package github.com/ipfs/go-datastore/query`

may be someone found solutions? 
I'm tried to fix this 3 day - i tried other version, add IPFS version to env, and a lot other, but failed anyway. 

ps.
https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins 
and
https://github.com/ipfs/go-ds-s3#building-and-installing

this not helped  - i done step-by-step, but still error

**Comment by aschmahmann** [comment]
Try building go-ipfs as preloaded plugin rather than as a separate .so object, it's much easier to do correctly since otherwise you have to be careful to build with the exact same versions of everything https://github.com/ipfs/go-ipfs/blob/master/docs/plugins.md#preloaded-plugins
