### ISSUE TITLE
can one IPFS instance uses multiple s3 buckets

### ISSUE THREAD

**Issue by Funarp** [ipfs/go-ds-s3#240]
Hi, I'm trying use MinIO as a s3 provider, sadly MinIO not support bucket scaling up, can one IPFS instance uses multiple s3 buckets when one is full? Hot to configure it?

**Comment by koxon** [comment]
S3 Buckets don't get full. If you're talking about reaching max throughput you can see this #205 discussion.
Referencing [this post](https://github.com/ipfs/go-ds-s3/issues/105) I think one bucket is enough. 

You can multiple the number of nodes, each pointing to a different bucket.
