### ISSUE TITLE
Which version match ipfs v0.20.0

### ISSUE THREAD

**Issue by Generalize** [ipfs/go-ds-s3#262]
I built go-ds-s3 with ipfs v0.20.0 and ran ipfs --version with an error
`Error: error loading plugins: plugin: s3-datastore-plugin, is duplicated in version: 0.0.1, while trying to load dynamically: 0.0.1`

**Comment by lidel** [comment]
@Generalize is this still happening with 0.21.0?

**Comment by lidel** [comment]
Assuming no longer a problem, if so, upgrade to  >0.21 and open a new issue.
