### ISSUE TITLE
trouble building for 0.4.22

### ISSUE THREAD

**Issue by spaceportpw** [ipfs/go-ds-s3#33]
After build ipfs and go-ds-s3 when i try to launch ipfs - i got an error: 
```plugin was built with a different version of package github.com/jbenet/goprocess```

My steps:
```git clone https://github.com/ipfs/go-ipfs
cd go-ipfs/
git checkout v0.4.22
make build IPFS_VERSION=v0.4.22
cp cmd/ipfs/ipfs /usr/local/bin/ipfs
ipfs version
cd ..
git clone https://github.com/ipfs/go-ds-s3
cd go-ds-s3
make go.mod IPFS_VERSION=v0.4.22
make build IPFS_VERSION=v0.4.22
mkdir -p ~/.ipfs/plugins
cp s3plugin.so ~/.ipfs/plugins/go-ds-s3.so
ipfs version
```

Environments:
```
GOARCH="amd64"
GOHOSTOS="linux"
GOPATH="/home/alex/go"
GOROOT="/usr/local/go"
```

Could you write steps of building s3 plugin correctly?

**Comment by Stebalien** [comment]
1. If you installed go-ipfs from dist.ipfs.io or built go-ipfs using `go get` (go modules), set IPFS_VERSION to the version you built (e.g., v0.4.22).
2. If you built go-ipfs from source, set IPFS_VERSION to `/path/to/local/ipfs/checkout`

**Comment by Stebalien** [comment]
_Or_ you could add `s3ds github.com/ipfs/go-ds-s3/plugin 0` to `plugin/loader/preload_list` in the go-ipfs source and then rebuild go-ipfs. This will build the plugin into go-ipfs so you can bypass this mess.

**Comment by Stebalien** [comment]
Improved install instructions: https://github.com/ipfs/go-ds-s3/pull/34

**Comment by spaceportpw** [comment]
After using this variant 
```
Or you could add s3ds github.com/ipfs/go-ds-s3/plugin 0 to plugin/loader/preload_list in the go-ipfs source and then rebuild go-ipfs. This will build the plugin into go-ipfs so you can bypass this mess.
```
where is can find s3plugin.so ?
or it's iside ipfs app?

**Comment by Stebalien** [comment]
> is it possible to replace all folders from $IPFS_DATA folder to s3? (/blocks, /datastore, /keystore)?

* /blocks should no longer be necessary (you can delete it)
* /datastore stores everything not in /blocks. It's _possible_ to store this on amazon but I recommend against it as performance will be poor.
* /keystore, etc. Not at the moment.

**Comment by Stebalien** [comment]
https://github.com/ipfs/go-ds-s3/pull/36
