### ISSUE TITLE
Support continuations

### ISSUE THREAD

**Issue by Stebalien** [ipfs/go-ds-s3#4]
See: https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

Otherwise, we'll fail to list datastores with over 1000 items (any sane datastore).

**Comment by ianopolous** [comment]
What are the consequences of this not being implemented? Is it just an optimisation, or does it mean the plugin can't handle more than 1000 objects in the datastore?

**Comment by Stebalien** [comment]
It meant that GC, repo list, etc. would fail when we hit 1000 objects. However, this has since been fixed.
