### ISSUE TITLE
version for ipfs release v0.4.23

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ds-s3#59]
@Stebalien Could we get a known good version for the latest ipfs release?

Many thanks!

**Comment by ianopolous** [comment]
Even better would be to have corresponding builds of this on dist.ipfs.io

**Comment by hsanjuan** [comment]
Can you check if c8aa80c8ee3c311c1a93307484262d2802d8dab6 works?

**Comment by ianopolous** [comment]
I tried compiling against go-ipfs v0.4.23
> make IPFS_VERSION=/home/ian/go/src/github.com/ipfs/go-ipfs
./set-target.sh /home/ian/go/src/github.com/ipfs/go-ipfs
go: cannot find main module, but found Gopkg.lock in /home/ian/go-ds-s3
	to create a module there, run:
	go mod init
Makefile:20: recipe for target 'go.mod' failed

**Comment by hsanjuan** [comment]
I'll try to make a 0.4.23 branch this week

**Comment by Stebalien** [comment]
@ianopolous please try running `make install` under the `release/v0.4.23` branch.

**Comment by ianopolous** [comment]
Thank you so much! I can confirm that works with ipfs 0.4.23 in our setup.
