### ISSUE TITLE
plugin was built with a different version of package github.com/jbenet/goprocess

### ISSUE THREAD

**Issue by naimbob95** [ipfs/go-ds-s3#87]
Hello, Sorry if this question is dupe.
However I am using go-ds-s3 checkout v0.4.23 and go-ipfs v0.4.23 that I download from
https://dist.ipfs.io/go-ipfs/v0.4.23/go-ipfs_v0.4.23_linux-amd64.tar.gz.
However I got this error.  Did i did something wrong with this?

`root@karnetif01:~/go-ds-s3# make install
./set-target.sh v0.4.23
go build  -asmflags=all=-trimpath="/root/work" -gcflags=all=-trimpath="/root/work" -buildmode=plugin -o "s3plugin.so" "plugin/main/main.go"
chmod +x "s3plugin.so"
Built against v0.4.23
install -Dm700 s3plugin.so "/root/.ipfs/plugins/go-ds-s3.so" 
root@karnetif01:~/go-ds-s3# ipfs version
Error: error loading plugins: loading plugin /root/.ipfs/plugins/go-ds-s3.so: plugin.Open("/root/.ipfs/plugins/go-ds-s3"): plugin was built with a different version of package github.com/jbenet/goprocess
root@karnetif01:~/go-ds-s3#
`

**Comment by Stebalien** [comment]
Did you checkout the `release/v0.4.23` branch? Also, please consider upgrading to 0.5.0.

**Comment by naimbob95** [comment]
yes i am checkout on release/v0.4.23, so I am installing v0.5.0 using https://dist.ipfs.io/go-ipfs/v0.5.0/go-ipfs_v0.5.0_linux-amd64.tar.gz

will not have the problem right?

**Comment by naimbob95** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/13710927/81151034-2cb1f700-8fb3-11ea-8275-0f2722b7f450.png)

So i have install ipfs v0.5.0 using this link: https://dist.ipfs.io/go-ipfs/v0.5.0/go-ipfs_v0.5.0_linux-amd64.tar.gz

and go-ds-s3 on v0.5.0

why still I have the same problem?

**Comment by naimbob95** [comment]
I am very sorry, i have solve this. This is because on my ubuntu running go version 1.4 while ipfs running go version 1.3.7..so I change the go version in my ubuntu and now it works with Digital Ocean Spaces.

Another question, can I save the file in the folder of the bucket instead of root bucket itself?
