### ISSUE TITLE
Error loading plugin with ipfs v0.6.0

### ISSUE THREAD

**Issue by ianopolous** [ipfs/go-ds-s3#98]
I've built the plugin against go-ipfs v0.6.0 (with go 1.14.4), but it fails to load with:

> plugin was built with a different version of package github.com/ipfs/go-ipfs/core/bootstrap

All I did was change go.mod in master to point to go-ipfs v0.6.0 and build with
> make IPFS_VERSION=/home/ian/go-ipfs build

(and go ipfs dir had checked out the v0.6.0 tag)

**Comment by ianopolous** [comment]
This is starting to smell like another GOFLAGS issue like https://github.com/ipfs/go-ds-s3/issues/63

**Comment by Stebalien** [comment]
If you're using a pre-built go-ipfs distribution, you need `make IPFS_VERSION=v0.6.0`. Only pass a path if you built go-ipfs from source (with `make build` inside the go-ipfs repo).

Where are you fetching go-ipfs?

---

The following work:

```
> cd /path/to/go-ipfs-repo
> make install
> cd /path/to/plugin
> make IPFS_VERSION=/path/to/go-ipfs-repo install
```

```
> ipfs-update install v0.6.0
> cd /path/to/plugin
> make IPFS_VERSION=v0.6.0 install
```

**Comment by ianopolous** [comment]
Thanks! That fixes it. I was using the pre-built go-ipfs version. I thought that pointing to the matching tag in a local path would be equivalent.

**Comment by Stebalien** [comment]
Oh, I wish.
